### ISSUE TITLE
这个项目和其他几个CLI云音乐的区别？

### ISSUE THREAD

**Issue by wzpan** [pi-dan/musicbox#1]
* [darknessomi/musicbox](https://github.com/darknessomi/musicbox)
* [bluetomlee/NetEase-MusicBox](https://github.com/bluetomlee/NetEase-MusicBox)

实在 confusing 。

**Comment by pi-dan** [comment]
这里面是有故事的，最开始有位大神做了一个云音乐（主公），然后被网易水表下架了，主公没了，群雄并起，加入了自己的想法，就出现了很多的版本了

**Comment by wzpan** [comment]
但好像都看不到对vellow的credit，甚至连commit都没了？不知道主公怎么想，成了无名英雄。

**Comment by pi-dan** [comment]
确实是成了无名英雄
